[project]
name = "fast-api-react"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "fastapi>=0.121.1",
    "pydantic-settings>=2.12.0",
    "uvicorn>=0.38.0",
]
